### ISSUE TITLE
After republishing data package, frontend keeps showing loading message

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend#71]
After republishing same data package with changing some properties in metadata(it is valid), it passes `pipeline`, but in `frontend` it keeps showing `Your data is safely stored and is getting processed - it will be here soon!`. 
Probably, `frontend` uses `pipeline` API to get the status of data package, but somehow,  #`pipeline's` status is not working properly. 
This is sample data package:
On site: https://testing.datahub.io/core/natural-gas
In pipeline: http://api-testing.datahub.io/pipelines/#anchor-ALL-b6c7c7180404aeb2863e592a9a72deb9-natural-gas

This is api call which `frontend` made to get status:
https://api-testing.datahub.io/source/core/natural-gas/status

It has `"modified": "2017-08-08T10:20:58.836555"` , but in pipeline console is `"modified": "2017-08-16T06:21:22.988024"`.

**Comment by anuveyatsu** [comment]
As you can see the response from https://api-testing.datahub.io/source/core/natural-gas/status has:

```
"state": "REGISTERED"
```

which should be one of `FAILED` or `SUCCEEDED` once pipelines terminated. @akariv can you take a look, please

**Comment by anuveyatsu** [comment]
Just took a look and found out the following:
In https://github.com/datahq/specstore/blob/b4bbf554869230fdc2664a41524dc834f331dd2e/specstore/controllers.py#L77-L78 we can see that `state` set to `REGISTERED` when update time of pipeline is older than update time of spec. So I have tested with one package to see what happens when I just repush my dataset without any changes:

In https://api.datahub.io/source/90998f7f90e086bd5fc7c9075dfda43b/co2-ppm/info `update_time` is the first pushed time:
```
{
  ...
  "pipeline": {
    "pipeline": [...],
    "update_time": "2017-08-15T05:54:36.488076"
  },
  ...
}
```

But if we take a look at `specs` table in the database, we can see that `updated_at` value is the date of the last push (`2017-08-29`). So because of that we are always getting TRUE in the following statement:

```python
if spec.updated_at and spec.updated_at.isoformat() > update_time:
    resp['state'] = 'REGISTERED'
```

**Comment by rufuspollock** [comment]
@anuveyatsu can you open this as a bug on the specstore and we'll wait for clarification from @akariv

**Comment by anuveyatsu** [comment]
Opened issue in specstore - https://github.com/datahq/specstore/issues/4

**Comment by anuveyatsu** [comment]
FIXED in upstream repo - https://github.com/datahq/specstore/issues/4
